---
deployment:
 tasks:
 - export DEPLOYPATH=/home/thediagr/public_html/
 - /bin/cp/cp -R about $DEPLOYPATH
 - /bin/cp/cp -R categories $DEPLOYPATH
 - /bin/cp/cp -R css $DEPLOYPATH
 - /bin/cp/cp -R images $DEPLOYPATH 
 - /bin/cp/cp -R js $DEPLOYPATH
 - /bin/cp/cp -R posts $DEPLOYPATH
 - /bin/cp/cp -R tags $DEPLOYPATH
 - /bin/cp/cp -R index.xml $DEPLOYPATH
 - /bin/cp/cp -R index.html $DEPLOYPATH
 - /bin/cp/cp -R sitemap.xml $DEPLOYPATH